from enum import Enum


class ResumeSectionType(str, Enum):
    HEADER = "HEADER",
    PROFESSIONAL_SUMMARY = "PROFESSIONAL SUMMARY",
    TECHNICAL_SKILLS = "TECHNICAL SKILLS",
    PROFESSIONAL_EXPERIENCE = "PROFESSIONAL EXPERIENCE",
    EDUCATION = "EDUCATION",
    PROFESSIONAL_DEVELOPMENT_OR_AFFILIATIONS = "PROFESSIONAL DEVELOPMENT/AFFILIATIONS"